/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as AppImport } from './pages/_app'
import { Route as AppIndexImport } from './pages/_app/index'
import { Route as AppStepStepNumberEntryNumberImport } from './pages/_app/step.$stepNumber.$entryNumber'

// Create Virtual Routes

const SigninLazyImport = createFileRoute('/signin')()

// Create/Update Routes

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/signin.lazy').then((d) => d.Route))

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppStepStepNumberEntryNumberRoute =
  AppStepStepNumberEntryNumberImport.update({
    path: '/step/$stepNumber/$entryNumber',
    getParentRoute: () => AppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/step/$stepNumber/$entryNumber': {
      id: '/_app/step/$stepNumber/$entryNumber'
      path: '/step/$stepNumber/$entryNumber'
      fullPath: '/step/$stepNumber/$entryNumber'
      preLoaderRoute: typeof AppStepStepNumberEntryNumberImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppStepStepNumberEntryNumberRoute: typeof AppStepStepNumberEntryNumberRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppStepStepNumberEntryNumberRoute: AppStepStepNumberEntryNumberRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/': typeof AppIndexRoute
  '/step/$stepNumber/$entryNumber': typeof AppStepStepNumberEntryNumberRoute
}

export interface FileRoutesByTo {
  '/signin': typeof SigninLazyRoute
  '/': typeof AppIndexRoute
  '/step/$stepNumber/$entryNumber': typeof AppStepStepNumberEntryNumberRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/step/$stepNumber/$entryNumber': typeof AppStepStepNumberEntryNumberRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/signin' | '/' | '/step/$stepNumber/$entryNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/' | '/step/$stepNumber/$entryNumber'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/'
    | '/_app/step/$stepNumber/$entryNumber'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/signin"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/step/$stepNumber/$entryNumber"
      ]
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/step/$stepNumber/$entryNumber": {
      "filePath": "_app/step.$stepNumber.$entryNumber.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
